// Src/Web/Client/src/Routes/Home/Home.tsx
import React, { useState } from "react";
import "./Home.css"

export default function Home() {
    const [redirect, setRedirect] = useState(false);
    const [redirectUrl, setRedirectUrl] = useState("");

    let login = async () => {
        if (!redirect) {
            try {
                const response = await fetch("http://localhost:8080/api/auth");
                const data = await response.json();
                if (!data.success) return alert("An error occurred!");
                setRedirect(true);
                setRedirectUrl(data.redirect);
            } catch (error) {
                console.log(error);
            }
        }
    };

    if (redirect && redirectUrl !== "") {
        window.location.href = redirectUrl;
    }
        return (
            <div className="main">
                <div className="animation">
                    <div className="star"/>
                    <div className="star"/>
                    <div className="star"/>
                    <div className="star"/>
                    <div className="star"/>
                </div>
                <div className="container">
                    <div className="menu">
                        <ul>
                            <li className="active">Home</li>
                            <li>Bot Info</li>
                            <li>Server Info</li>
                            <li>Invite Bot</li>
                            <li>Join Server</li>
                        </ul>
                    </div>

                <div className="btn">
                    <button onClick={() => login()} className="button">Login</button>
                </div>

                <div className="banner">
                    <div className="app-text">
                        <h1>Meet Blazify, <br/> a Feature Rich Discord Bot</h1>
                        <p>
                            Blazify is a new Discord Bot that started development in March of 2020, and we are proud to
                            announce that it is now a fully fledged multi-purpose Discord Bot. Click on "Bot Info" to
                            learn more.
                        </p>
                        <div className="play-btn">
                            <div className="play-btn-inner">
                                <i className="fa fa-play"/></div>
                        </div>
                        <small><b>Learn More</b></small>
            </div>
                </div>
                    <div className="quick-link">
                        <ul>
                            <li><i className="fa fa-share-alt"/><p>Share others</p></li>
                            <li><i className="fa fa-audio-description"/><p>Chat App</p></li>
                            <li><i className="fa fa-cog"/><p>System Stats of VPS</p></li>
                        </ul>
                    </div>
                    <div className="social-media-icons">
                        <ul>
                            <li><a href="https://twitter.com/ABlazify"><i className="fa fa-twitter"/></a></li>
                            <li><a href="https://instagram.com/b3_romeah_yt"><i className="fa fa-instagram"/></a></li>
                            <li><a href="https://gmail.com"><i className="fa fa-envelope"/></a></li>
                        </ul>
                    </div>
                    </div>
            </div>
        )
}

// Src/Web/Client/src/views/Home.vue
<template>
    <div class="main">
        <div class="animation">
        <div class="star"></div>
        <div class="star"></div>
        <div class="star"></div>
        <div class="star"></div>
        <div class="star"></div>
    </div>

        <div class="container">
            <div class="menu">
                <ul>
                    <li class="logo"><img src="../assets/logo.png"></li>
                    <li class="active">Home</li>
                    <li>Bot Info</li>
                    <li>Server Info</li>
                    <li>Invite Bot</li>
                    <li>Join Server</li>
                </ul>
                <div class="btn">
                    <button class="button" @click="login()">Login</button>
                </div>
            </div>

            <div class="banner">
                <div class="app-text">
                    <h1>Meet Blazify, <br> a Feature Rich Discord Bot </h1>
                    <p>
                        Blazify is a new Discord Bot that started development in March of 2020, and we are proud to announce that it is now a fully fledged multi-purpose Discord Bot. Click on "Bot Info" to learn more.
                    </p>
                    <div class="play-btn">
                        <div class="play-btn-inner">
                            <i class="fa fa-play"></i></div>
                    </div>
                    <small><b>Learn More</b></small>
                </div>
                <div class="app-pic">
                    <img src="../assets/logo.png" alt="logo">
                </div>
            </div>
            <div class="quick-link">
                <ul>/
                    <li><i class="fa fa-share-alt"></i><p>Share others</p></li>
                    <li><i class="fa fa-audio-description"></i><p>Chat App</p></li>
                    <li><i class="fa fa-cog"></i><p>System Stats of VPS</p></li>
                </ul>
            </div>
            <div class="social-media-icons">
                <ul>
                    <li><a href="#"><i class="fa fa-twitter"></i></a> </li>
                    <li><a href="#"><i class="fa fa-instagram"></i></a> </li>
                    <li><a href="#"><i class="fa fa-envelope"></i></a> </li>
                </ul>
            </div>
        </div>
    </div>
</template>
<script>
    export default {
        name: "Home",
        methods: {
            login : function () {
                fetch ( "http://localhost:8080/api/auth" )
                    .then ( res => res.json () )
                    .then ( body => {
                        if (!body.success) return alert ( "An error occurred!" );
                        location.href = body.redirect;
                    } );
            }
        }
    }
</script>
<style>

    *{
        margin: 0;
        padding: 0;
        font-family: sans-serif;
    }
    .main{
        height: 100vh;
        display: flex;
        justify-content: center;
        align-items: center;
        background: radial-gradient(ellipse at bottom, #0D1E31, #111);
        overflow: hidden;
    }

    .animation{
        position: absolute;
        width: 100%;
        height: 100%;
        left: -50px;
        transform: rotateZ(40deg);
    }

    .star{
        position: absolute;
        left: -300%;
        top: 50%;
        height: 4px;
        background: linear-gradient(-45deg, #5F91FF, rgba(0, 0, 255, 0));
        border-radius: 999px;
        filter: drop-shadow(0 0 6px #699BFF);
        animation: tail 3s ease-in-out infinite,
        falling 3s ease-in-out infinite;
    }

    @keyframes tail{
        0%{
            width: 0;
        }
        30%{
            width: 100px;
        }
        100%{
            width: 0;
        }
    }

    @keyframes falling{
        0%{
            transform: translateX(0);
        }
        100%{
            transform: translateX(300px);
        }
    }

    .star::before, .star::after{
        content: '';
        position: absolute;
        top: calc(50% - 2px);
        right: 0;
        height: 4px;
        background: linear-gradient(-45deg, rgba(0, 0, 255, 0), #5F91FF, rgba(0, 0, 255, 0));
        border-radius: 100%;
        transform: translateX(50%) rotateZ(45deg);
        animation: shining 3s ease-in-out infinite;
    }

    @keyframes shining{
        0%{
            width: 0;
        }
        50%{
            width: 30px;
        }
        100%{
            width: 0;
        }
    }

    .star::after{
        transform: translateX(50%) rotateZ(-45deg);
    }

    .star:nth-child(1){
        top: calc(50% - 100px);
        left: calc(50% - 250px);
        animation-delay: 1s;
    }

    .star:nth-child(1)::before, .star:nth-child(1)::after{
        animation-delay: 1s;
    }

    .star:nth-child(2){
        top: calc(50% - 50px);
        left: calc(50% - 200px);
        animation-delay: 1.2s;
    }

    .star:nth-child(2)::before, .star:nth-child(2)::after{
        animation-delay: 1.2s;
    }

    .star:nth-child(3){
        top: calc(50% - 0px);
        left: calc(50% - 150px);
        animation-delay: 1.4s;
    }

    .star:nth-child(3)::before, .star:nth-child(3)::after{
        animation-delay: 1.4s;
    }

    .star:nth-child(4){
        top: calc(50% - -50px);
        left: calc(50% - 200px);
        animation-delay: 1.6s;
    }

    .star:nth-child(4)::before, .star:nth-child(4)::after{
        animation-delay: 1.6s;
    }

    .star:nth-child(5){
        top: calc(50% - -100px);
        left: calc(50% - 250px);
        animation-delay: 1.8s;
    }

    .star:nth-child(5)::before, .star:nth-child(5)::after{
        animation-delay: 1.8s;
    }
    .container{
        width: 100%;
        height: 100%;
        left: 100px;
    }
    .menu ul{
        display: inline-flex;
        margin: 20px;
    }
    .menu ul li{
        list-style: none;
        margin: 0 20px;
        color: #b2b1b1;
        cursor: pointer;
    }
    .logo img{
        width: 30px;
        margin-top: -7px;
        margin-right: -50px;
    }
    .active{
        color: #19dafa !important;
    }
    .banner{
        width: 80%;
        height: 70%;
        top: 25%;
        left: 130px;
        position: absolute;
        color: #fff;
    }
    .app-text{
        width: 50%;
        float: left;
    }
    .app-text h1{
        font-size: 43px;
        width: 640px;
        position: relative;
        margin-left: -2px;
    }
    .app-text p{
        width: 650px;
        font-size: 15px;
        margin: 20px 0 20px -50px;
        line-height: 25px;
        color: #919191;
    }
    .app-pic{
        width: 50%;
        float: left;
    }
    .app-pic img{
        width: 100%;
        margin-top: -20px;
        padding-left: 55px;
    }
    .play-btn{
        margin-left: 40px;
        display: inline-flex;
    }
    .play-btn-inner{
        height: 50px;
        width: 50px;
        border: 2px solid transparent;
        border-radius: 50%;
        background-image: linear-gradient(#42455a,#42455a),radial-gradient(circle at top left, #fd00da,#19d7f8);
        background-origin: border-box;
        background-clip: content-box, border-box;
        text-align: center;
    }
    .play-btn-inner .fa{
        padding: 18px 0;
        font-size: 13px;
        cursor: pointer;
    }
    small{
        margin: auto 20px;
        cursor: pointer;
        font-size: 12px;
        color: #19dafa;
        letter-spacing: 3px;
    }
    .quick-link{
        left: 0;
        bottom: 0;
        position: absolute;
        background: linear-gradient(to right, #db1bf6,#19d7f8);
    }
    .quick-link ul{
        display: inline-flex;
        margin: 25px auto;
        text-align: center;
    }
    .quick-link ul li{
        list-style: none;
        margin: 0 50px;
        cursor: pointer;
    }
    .quick-link ul li .fa{
        font-size: 25px;
        color: #fff;
    }
    .quick-link ul li p{
        margin-top: 15px;
        font-size: 10px;
        color: #fff;
    }
    .social-media-icons{
        right: 62px;
        bottom: 35px;
        position: absolute;
    }
    .social-media-icons ul li{
        list-style: none;
        margin-top: 15px;
        text-align: center;
    }
    .social-media-icons ul li a{
        color: #ffffff;
        border-radius: 50%;
        border: 1px solid #999;
        padding: 5px;
        display: block;
    }
    .btn {
        height: 10%;
        display: flex;
        align-items: center;
        justify-content: center;
    }
    .button {
        top: -50px;
        left: 450px;
        min-width: 280px;
        min-height: 74px;
        font-family: "Nunito", sans-serif;
        font-size: 22px;
        text-transform: uppercase;
        letter-spacing: 1px;
        font-weight: 700;
        color: #313133;
        background: #4f5cd1;
        background: linear-gradient(to right, #19d7f8,#db1bf6);
        border: none;
        box-shadow: 5px 5px 15px rgba(79, 209, 190, 0.64);
        transition: all 0.3s ease-in-out 0s;
        cursor: pointer;
        outline: none;
        position: relative;
        padding: 10px;
    }
    .button::before {
        content: '';
        min-width: calc(275px + 12px);
        min-height: calc(60px + 12px);
        border: 6px solid #00FFCB;
        box-shadow: 0 0 60px rgba(0, 255, 203, .64);
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        opacity: 0;
        transition: all .3s ease-in-out 0s;
    }
    .button:hover, .button:focus {
        color: #313133;
        transform: translateY(-6px);
    }
    button:hover::before, button:focus::before {
        opacity: 1;
    }
    button::after {
        animation: ring 1.5s infinite;
        width: 30px; height: 30px;
        border-radius: 100%;
        border: 6px solid #002ccb;
        position: absolute;
        z-index: -1;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }
    @keyframes ring {
        0% {
            width: 30px;
            height: 30px;
            opacity: 1;
        }
        100% {
            width: 300px;
            height: 300px;
            opacity: 0;
        }
    }
</style>
